baseURL = "https://samziegler.me/"
languageCode = "en-us"
title = "Sam Ziegler's Homepage"
theme = "hugo-coder"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  author = "Sam Ziegler"
  info = "Machine Learning Engineer"
  description = "Sam Ziegler's Homepage"
  keywords = "developer,personal"
  colorsheme = "auto"
  avatarurl = "images/sam_on_beach.jpg"
  hidecolorschemetoggle = true

  enableTwitterShare = true  # new add

[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/thesamziegler/"

[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/samuel-ziegler-9567ab18/"

# Menu links

[[menu.main]]
  name = "Blog"
  weight = 2
  url  = "posts/"
