baseURL = "http://samziegler.me"
languageCode = "en"
title = "Sam Ziegler's Homepage"
theme = "hugo-coder"
defaultContentLanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  author = "Sam Ziegler"
  info = ""
  description = "Sam Ziegler's Homepage"
  keywords = "developer,personal"
  avatarurl = "images/sam_on_beach.jpg"
  katex = true

  enableTwitterShare = true  # new add

  customSCSS = ["fork-awesome/fork-awesome.scss"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
  name = "Twitter"
  icon = "fa fa-2x fa-twitter"
  weight = 1
  url = "https://twitter.com/thesamziegler/"

[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-2x fa-linkedin"
  weight = 2
  url = "https://www.linkedin.com/in/samuel-ziegler-9567ab18/"

[[params.social]]
  name = "Soundcloud"
  icon = "fa fa-2x fa-soundcloud"
  weight = 3
  url = "https://soundcloud.com/sam-ziegler-1/"

# Menu links

[languages.en]
languageName = ":us:"

[[languages.en.menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
